apiVersion: v1
kind: Service
metadata:
  name: env-redis
  labels:
    mibexx-svc: env_redis
spec:
  type: ClusterIP
  externalName: env-redis
  ports:
    - port: 6379
      protocol: TCP
  selector:
    mibexx-env: env_redis
