apiVersion: v1
kind: Service
metadata:
  name: env-elasticsearch
  labels:
    mibexx-svc: env_elasticsearch
spec:
  type: NodePort
  ports:
    - port: 9200
      protocol: TCP
  selector:
    mibexx-env: env_elasticsearch
