apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-jenkins
  labels:
    mibexx-env: env_jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      mibexx-env: env_jenkins
  template:
    metadata:
      labels:
        mibexx-env: env_jenkins
    spec:
      volumes:
        - name: spryker-b2b-storage
          persistentVolumeClaim:
            claimName: spryker-b2b-claim
      containers:
        - name: env-jenkins
          image: mibexx/k8s-jenkins:7.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/srv/spryker"
              name: spryker-b2b-storage
