apiVersion: v1
kind: Service
metadata:
  name: env-jenkins
  labels:
    mibexx-svc: env_jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
  selector:
    mibexx-env: env_jenkins
