apiVersion: v1
kind: Service
metadata:
  name: app-glue
  labels:
    mibexx-svc: spryker_b2b_glue
spec:
  type: ClusterIP
  externalName: app-glue
  ports:
    - port: 80
      protocol: TCP
  selector:
    mibexx-app: spryker_b2b_glue
