apiVersion: v1
kind: Service
metadata:
  name: lb-sprykerb2b
  labels:
    mibexx-svc: spryker_b2b_loadbalancer
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
  selector:
    mibexx-app: spryker_b2b_loadbalancer
