apiVersion: v1
kind: PersistentVolume
metadata:
  name: spryker-b2b
  labels:
    mibexx-vol: spryker-b2b
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/spryker-b2b"


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spryker-b2b-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
