apiVersion: v1
kind: Service
metadata:
  name: app-zed
  labels:
    mibexx-svc: spryker_b2b_zed
spec:
  type: ClusterIP
  externalName: app-zed
  ports:
    - port: 80
      protocol: TCP
  selector:
    mibexx-app: spryker_b2b_zed
