apiVersion: v1
kind: Service
metadata:
  name: env-postgres
  labels:
    mibexx-svc: env_postgres
spec:
  type: ClusterIP
  externalName: env-postgres
  ports:
    - port: 5432
      protocol: TCP
  selector:
    mibexx-env: env_postgres
