apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-rabbitmq
  labels:
    mibexx-env: env_rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      mibexx-env: env_rabbitmq
  template:
    metadata:
      labels:
        mibexx-env: env_rabbitmq
    spec:
      containers:
        - name: env-rabbitmq
          image: rabbitmq:3.7-management-alpine
          imagePullPolicy: IfNotPresent
          ports:
              - containerPort: 5672
              - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "mibexx"
            - name: RABBITMQ_DEFAULT_PASS
              value: "mBx.123"
