apiVersion: v1
kind: Service
metadata:
  name: env-rabbitmq
  labels:
    mibexx-svc: env_rabbitmq
spec:
  type: NodePort
  ports:
    - port: 5672
      name: service
      protocol: TCP
    - port: 15672
      name: management
      protocol: TCP
  selector:
    mibexx-env: env_rabbitmq
